<?php

namespace CommunityDS\Deputy\Api\Model;

interface CompanySettingsInterface
{
    /**
     * Scheduling settings
     */
    const SETTING_WEEK_START = 'WEEK_START';
    const SETTING_ACTIVE_HOURS_START = 'ACTIVE_HOURS_START';
    const SETTING_ACTIVE_HOURS_END = 'ACTIVE_HOURS_END';
    const SETTING_ROSTER_DEFAULT_SHIFT_LEN = 'ROSTER_DEFAULT_SHIFT_LEN';
    const SETTING_DEFAULT_MEALBREAK_DURATION = 'DEFAULT_MEALBREAK_DURATION';
    const SETTING_SHIFT_COST_ADDITIONAL = 'SHIFT_COST_ADDITIONAL';
    const SETTING_ROSTER_PREVENT_CHANGE_HOURS = 'ROSTER_PREVENT_CHANGE_HOURS';
    const SETTING_ROSTER_NOTIFICATION_MANAGER = 'ROSTER_NOTIFICATION_MANAGER';
    const SETTING_ROSTER_REQUIRE_CONFIRM_HOURS = 'ROSTER_REQUIRE_CONFIRM_HOURS';
    const SETTING_ROSTER_RECOMMENDATION_SORTING = 'ROSTER_RECOMMENDATION_SORTING';
    const SETTING_ROSTER_ALLOW_PEER_VIEW = 'ROSTER_ALLOW_PEER_VIEW';
    const SETTING_ROSTER_ALLOW_SWAP_SHIFT = 'ROSTER_ALLOW_SWAP_SHIFT';
    const SETTING_ROSTER_SWAP_REQUIRE_APPROVAL = 'ROSTER_SWAP_REQUIRE_APPROVAL';
    const SETTING_ROSTER_ALLOW_OFFER_SHIFT = 'ROSTER_ALLOW_OFFER_SHIFT';
    const SETTING_ROSTER_ALLOW_SMS_WITH_FULL_NAME = 'ROSTER_ALLOW_SMS_WITH_FULL_NAME';
    
    /**
     * Timesheet settings
     */
    const SETTING_CAN_BUMP_SHIFT_VIA_DESK = 'CAN_BUMP_SHIFT_VIA_DESK';
    const SETTING_CAN_MOBILE_BUMP_SHIFT = 'CAN_MOBILE_BUMP_SHIFT';
    const SETTING_CAN_SMS_BUMP_SHIFT = 'CAN_SMS_BUMP_SHIFT';
    const SETTING_REQUIRE_KIOSK_PHOTO_BUMP_SHIFT = 'REQUIRE_KIOSK_PHOTO_BUMP_SHIFT';
    const SETTING_CAN_SUBMIT_SHIFT_VIA_DESK = 'CAN_SUBMIT_SHIFT_VIA_DESK';
    const SETTING_CAN_MODIFY_TIMESHEET_ON_END = 'CAN_MODIFY_TIMESHEET_ON_END';
    const SETTING_TIMESHEET_MATURITY = 'TIMESHEET_MATURITY';
    const SETTING_TIMESHEET_CLOSEST_BLOCK = 'TIMESHEET_CLOSEST_BLOCK';
    const SETTING_MEALBREAK_IS_PAID = 'MEALBREAK_IS_PAID';
    const SETTING_TIMESHEET_AUTO_ROUND = 'TIMESHEET_AUTO_ROUND';
    const SETTING_TIMESHEET_ROUND_START_TIME = 'TIMESHEET_ROUND_START_TIME';
    const SETTING_TIMESHEET_ROUND_END_TIME = 'TIMESHEET_ROUND_END_TIME';
    const SETTING_TIMESHEET_ROUND_MEALBREAK = 'TIMESHEET_ROUND_MEALBREAK';
    const SETTING_TIMESHEET_ROUND_START_TIME_RS = 'TIMESHEET_ROUND_START_TIME_RS';
    const SETTING_TIMESHEET_ROUND_END_TIME_RS = 'TIMESHEET_ROUND_END_TIME_RS';
    const SETTING_TIMESHEET_ROUND_MEALBREAK_RS = 'TIMESHEET_ROUND_MEALBREAK_RS';
    const SETTING_TIMESHEET_AUTO_TIME_APPROVE = 'TIMESHEET_AUTO_TIME_APPROVE';
    const SETTING_CAN_CLOCKIN_SHIFT_EARLIER = 'CAN_CLOCKIN_SHIFT_EARLIER';
    const SETTING_TIMESHEET_MATCH_ROSTER = 'TIMESHEET_MATCH_ROSTER';
    const SETTING_TIMESHEET_MATCH_ROSTER_TIME = 'TIMESHEET_MATCH_ROSTER_TIME';
    const SETTING_CAN_CLOCKIN_SHIFT_EARLIER_MINS = 'CAN_CLOCKIN_SHIFT_EARLIER_MINS';
    const SETTING_CAN_END_BREAK_EARLIER = 'CAN_END_BREAK_EARLIER';
    const SETTING_AUTO_SUGGEST_BREAK = 'AUTO_SUGGEST_BREAK';
    const SETTING_CAN_DISPLAY_BREAK_WARNING = 'CAN_DISPLAY_BREAK_WARNING';
}
