name: run-tests

on: [push, pull_request]

jobs:
    build-test:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest]
                php: [5.6, 8.1]

        steps:
            - uses: actions/checkout@v3

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  coverage: none

            - name: Install dependencies
              run: |
                  composer install --prefer-dist --no-interaction

            - name: Execute tests
              run: vendor/bin/phpunit
